import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase';
import { getUser } from '@/lib/auth/get-user';

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function generateBlueprintHtml(blueprint: any): string {
  const title = escapeHtml(blueprint.title || 'Untitled Blueprint');
  const strategy = escapeHtml(blueprint.strategy || 'N/A');
  const targetAudience = escapeHtml(blueprint.target_audience || 'N/A');
  const marketingPlan = escapeHtml(blueprint.marketing_plan || 'N/A');
  const pricingStrategy = escapeHtml(blueprint.pricing_strategy || 'N/A');
  const productTitle = escapeHtml(blueprint.products?.title || 'N/A');
  const productPrice = blueprint.products?.price ? `$${Number(blueprint.products.price).toFixed(2)}` : 'N/A';
  const productSource = escapeHtml(blueprint.products?.source || 'N/A');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    h1 { color: #1a56db; border-bottom: 2px solid #1a56db; padding-bottom: 10px; }
    h2 { color: #374151; margin-top: 30px; }
    .section { margin-bottom: 20px; padding: 15px; background: #f9fafb; border-radius: 8px; }
    .label { font-weight: bold; color: #6b7280; font-size: 12px; text-transform: uppercase; }
    .value { margin-top: 5px; font-size: 14px; line-height: 1.6; }
    .product-info { display: flex; gap: 20px; }
    .product-info div { flex: 1; }
    .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 10px; }
  </style>
</head>
<body>
  <h1>Launch Blueprint: ${title}</h1>

  <h2>Product Details</h2>
  <div class="section product-info">
    <div>
      <div class="label">Product</div>
      <div class="value">${productTitle}</div>
    </div>
    <div>
      <div class="label">Price</div>
      <div class="value">${productPrice}</div>
    </div>
    <div>
      <div class="label">Source</div>
      <div class="value">${productSource}</div>
    </div>
  </div>

  <h2>Strategy</h2>
  <div class="section">
    <div class="value">${strategy}</div>
  </div>

  <h2>Target Audience</h2>
  <div class="section">
    <div class="value">${targetAudience}</div>
  </div>

  <h2>Marketing Plan</h2>
  <div class="section">
    <div class="value">${marketingPlan}</div>
  </div>

  <h2>Pricing Strategy</h2>
  <div class="section">
    <div class="value">${pricingStrategy}</div>
  </div>

  <div class="footer">
    Generated by YouSell.Online on ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`;
}

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const user = await getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { id } = params;

  const { data: blueprint, error } = await supabaseAdmin
    .from('blueprints')
    .select('*, products(*)')
    .eq('id', id)
    .single();

  if (error || !blueprint) {
    return NextResponse.json({ error: 'Blueprint not found' }, { status: 404 });
  }

  const html = generateBlueprintHtml(blueprint);

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `attachment; filename="blueprint-${id}.html"`,
    },
  });
}
