import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { requireAdmin } from "@/lib/auth/roles";

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function generateBlueprintHtml(blueprint: Record<string, unknown>): string {
  const product = blueprint.products as Record<string, unknown> | null;
  const title = escapeHtml((product?.title as string) || 'Untitled Product');
  const platform = escapeHtml((product?.platform as string) || 'N/A');
  const score = product?.final_score ?? 'N/A';

  const sections = [
    { label: 'Market Positioning', value: blueprint.positioning },
    { label: 'Product Page Content', value: blueprint.product_page_content },
    { label: 'Pricing Strategy', value: blueprint.pricing_strategy },
    { label: 'Video Script', value: blueprint.video_script },
    { label: 'Ad Blueprint', value: blueprint.ad_blueprint },
    { label: 'Launch Timeline', value: blueprint.launch_timeline },
    { label: 'Risk Notes', value: blueprint.risk_notes },
  ];

  const sectionsHtml = sections
    .filter(s => s.value)
    .map(s => `
      <h2>${escapeHtml(s.label)}</h2>
      <div class="section">
        <div class="value">${escapeHtml(String(s.value))}</div>
      </div>
    `)
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Launch Blueprint: ${title}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    h1 { color: #1a56db; border-bottom: 2px solid #1a56db; padding-bottom: 10px; }
    h2 { color: #374151; margin-top: 30px; }
    .section { margin-bottom: 20px; padding: 15px; background: #f9fafb; border-radius: 8px; }
    .value { font-size: 14px; line-height: 1.6; white-space: pre-wrap; }
    .meta { display: flex; gap: 20px; margin-bottom: 20px; }
    .meta div { flex: 1; padding: 10px; background: #f0f9ff; border-radius: 6px; }
    .meta .label { font-weight: bold; color: #6b7280; font-size: 12px; text-transform: uppercase; }
    .meta .val { margin-top: 4px; font-size: 16px; font-weight: bold; }
    .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 10px; }
    @media print { body { margin: 20px; } .section { break-inside: avoid; } }
    @page { margin: 1.5cm; }
  </style>
</head>
<body>
  <h1>Launch Blueprint: ${title}</h1>
  <div class="meta">
    <div><div class="label">Platform</div><div class="val">${platform}</div></div>
    <div><div class="label">Score</div><div class="val">${score}</div></div>
    <div><div class="label">Generated</div><div class="val">${new Date(blueprint.generated_at as string).toLocaleDateString()}</div></div>
  </div>
  ${sectionsHtml}
  <div class="footer">Generated by YouSell.Online on ${new Date().toLocaleDateString()}</div>
</body>
</html>`;
}

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try { await requireAdmin(); } catch { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { id } = params;

  const { data: blueprint, error } = await supabase
    .from('launch_blueprints')
    .select('*, products(id, title, platform, final_score)')
    .eq('id', id)
    .single();

  if (error || !blueprint) {
    return NextResponse.json({ error: 'Blueprint not found' }, { status: 404 });
  }

  const html = generateBlueprintHtml(blueprint);

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `inline; filename="blueprint-${id}.html"`,
    },
  });
}
